FROM apache/airflow:2.6.3-python3.9

# Instale o Tor e outras dependências necessárias
USER root
RUN apt-get update && \
    apt-get install -y tor && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Retorne ao usuário padrão do Airflow
USER airflow
