services:
  jupyterlab:
    image: jupyter/pyspark-notebook:spark-3.3.0
    container_name: jupyterlab_pyspark
    ports:
      - "8888:8888"
    volumes:
      - ./jupyter_notebooks:/home/jovyan
      - ./jupyter_setup.sh:/usr/local/bin/jupyter_setup.sh:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /home/ubuntu/scrapper_v2:/home/ubuntu/scrapper_v2
    environment:
      JUPYTER_ENABLE_LAB: "yes"
      GRANT_SUDO: "yes"
      NB_UID: 1000
      NB_GID: 100
      SPARK_OPTS: "--packages io.delta:delta-core_2.12:2.2.0"
      TZ: "America/Sao_Paulo"
    user: root
    command: ["bash", "/usr/local/bin/jupyter_setup.sh"]

  postgres:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "meu_banco"
      TZ: "America/Sao_Paulo"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - jupyterlab

  airflow:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    container_name: airflow_server
    environment:
      AIRFLOW_HOME: "/opt/airflow"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://admin:admin@postgres:5432/meu_banco"
      AIRFLOW__CORE__EXECUTOR: "LocalExecutor"
      TZ: "America/Sao_Paulo"
    ports:
      - "8080:8080"
    volumes:
      - ./airflow:/opt/airflow
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./jupyter_notebooks:/home/jovyan
      - ./airflow_setup.sh:/usr/local/bin/airflow_setup.sh:ro
    depends_on:
      - postgres
      - jupyterlab
    entrypoint: >
      bash -c "
      bash /usr/local/bin/airflow_setup.sh &&
      airflow db init &&
      airflow users create --username admin --password admin --firstname John --lastname Doe --role Admin --email admin@example.com &&
      airflow webserver
      "
  
  airflow-scheduler:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    container_name: airflow_scheduler
    environment:
      AIRFLOW_HOME: "/opt/airflow"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://admin:admin@postgres:5432/meu_banco"
      AIRFLOW__CORE__EXECUTOR: "LocalExecutor"
      TZ: "America/Sao_Paulo"
    volumes:
      - ./airflow:/opt/airflow
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./jupyter_notebooks:/home/jovyan
      - ./airflow_scheduler_setup.sh:/usr/local/bin/airflow_scheduler_setup.sh:ro
    depends_on:
      - postgres
      - airflow
      - jupyterlab
    entrypoint: >
      bash -c "
      bash /usr/local/bin/airflow_scheduler_setup.sh &&
      airflow db init &&
      airflow scheduler
      "

volumes:
  postgres_data:
