source:
  type: postgres
  config:
    host_port: 172.21.0.2:5432
    database: meu_banco
    username: admin
    password: admin
sink:
  type: datahub-rest
  config:
    server: http://localhost:8080

